website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func
from flask_login import UserMixin



class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    studentId = db.Column(db.String(150))
    

class Sinhvien(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    studentId = db.Column(db.String(150))
    studentName = db.Column(db.String(150))
    dob = db.Column(db.String(150))
    course = db.Column(db.String(150))
    department = db.Column(db.String(150))
    studentClass = db.Column(db.String(150))
    nationalId = db.Column(db.String(150))
    issuedDt = db.Column(db.String(150))
    phone = db.Column(db.String(150))
    religion = db.Column(db.String(150))
    gender = db.Column(db.String(150))
    issuedPlace = db.Column(db.String(150))
    ethnic = db.Column(db.String(150))
    Address = db.Column(db.String(3000))
    dormId = db.Column(db.String(150))


  
    

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Sinhvien

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)


    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))


    return app


def create_database(app):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
import email
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Sinhvien, User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/')
def start():
    return redirect(url_for('auth.login'))


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            return redirect(url_for('auth.login'))

    return render_template("sign_up.html", user=current_user)

@auth.route('/dknoitru', methods=['GET', 'POST'])
@login_required
def dknoitru():
    if request.method == 'POST':
        email = request.form.get('email')
        studentId = request.form.get('studentId')
        studentName = request.form.get('studentName')
        dob = request.form.get('dob')
        course = request.form.get('course')
        department = request.form.get('department')
        studentClass = request.form.get('studentClass')
        nationalId = request.form.get('nationalId')
        issuedDt = request.form.get('issuedDt')
        phone = request.form.get('phone')
        religion = request.form.get('religion')
        gender = request.form.get('gender')
        issuedPlace = request.form.get('issuedPlace')
        ethnic = request.form.get('ethnic')
        Address = request.form.get('Address')
        dormId = request.form.get('dormId')
        sv = User.query.filter_by(email=email).first()
        if sv:
            new_sv = Sinhvien(email=email, studentId=studentId, studentName=studentName, dob=dob, course=course, department=department, 
            studentClass=studentClass, nationalId=nationalId, issuedDt=issuedDt, phone=phone, religion=religion, gender=gender, 
            issuedPlace=issuedPlace, ethnic=ethnic, Address=Address, dormId=dormId)
            db.create_all()
            db.session.add(new_sv)
            db.session.commit()
            return redirect(url_for('views.home'))
        else:
            flash('Email does not exist.', category='error')
    return render_template("dknoitru.html", user=current_user)


@auth.route('/dondk')
@login_required
def don():
    return render_template("dondk.html", values=Sinhvien.query.all())


@auth.route('/profile')
def profile():
    return render_template("profile.html", user=current_user)

#@auth.route('/thanhtoan', methods=['GET', 'POST'])
#@login_required
#def dknoitru():
#   if request.method == 'POST':
 #       studentId = request.form.get('studentId')
#        sv = User.query.filter_by(studentId=studentId).first()
#        if sv:
#            return redirect(url_for('auth.thanhtoan'))
#        else:
#            flash('Student does not exist.', category='error')
#    return render_template("thanhtoan.html", user=current_user)



website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from . import db
import json

views = Blueprint('views', __name__)


@views.route('/')
@login_required
def home():

    return render_template("home.html", user=current_user)



website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="{{ url_for('static', filename='FileCss/style.css')}}" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

   
    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

website/templates/dondk.html
{% extends "sidenav.html" %}

{% block content %}

{% for item in values %}
<html lang="en">
  <head>
    <meta name="description" content="Trang web quản lý KTX trường PTIT" />
    <title>Đăng ký nội trú - PTIT Admin</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='FileCss/dknoitru.css')}}" />

    <!-- Font-icon css-->
    <link
      rel="stylesheet"
      type="text/css"
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    
	<style>.tile .control-disabled {
      position: absolute;
      top: 0;
      left: 0;
      bottom: 0;
      right: 0;
      background-color: rgba(255, 255, 255, 0.36);
      display: -webkit-box;
      display: -ms-flexbox;
      display: flex;
      -webkit-box-align: center;
      -ms-flex-align: center;
      align-items: center;
      -webkit-box-pack: center;
      -ms-flex-pack: center;
      justify-content: center;
      -webkit-box-orient: horizontal;
      -webkit-box-direction: normal;
      -ms-flex-direction: row;
      flex-direction: row;
      color: rgb(210, 207, 207);
      border-radius: 3px;
      z-index: 999;
      }
	  .form-control::placeholder {
            color: #2b2727;
            opacity: 1;
			font-size: 100%;
			font-weight: bold;
        }
    </style>
  </head>
  <body class="app sidebar-mini pace-done sidenav-toggled">
    <form method="POST" action="{{url_for('auth.dknoitru')}}">
      <div class="pace pace-inactive">
        <div
          class="pace-progress"
          data-progress-text="100%"
          data-progress="99"
          style="transform: translate3d(100%, 0px, 0px)"
        >
          <div class="pace-progress-inner"></div>
        </div>
        <div class="pace-activity"></div>
      </div>
      <div id="overlay">
        <div class="cv-spinner"><span class="spinner"></span></div>
      </div>

      <main class="app-content">
        <div class="row"><div class="col-md-12"></div></div>
        <div class="app-title">
          <div>
            <h1><i class="fa fa-edit"></i> Đăng ký nội trú PTIT</h1>
            <p>Đơn đăng ký nội trú dành cho sinh viên</p>
          </div>
          <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
            <li class="breadcrumb-item">Biểu mẫu</li>
            <li class="breadcrumb-item"><a href="#">Đăng ký nội trú</a></li>
          </ul>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="tile">
              <div class="control-disabled"></div>
              <h3 class="mb-3 line-head">Biểu mẫu đăng ký nội trú</h3>
              <div class="tile-body">
                  <h4>Thông tin sinh viên</h4>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="studentId"
                          >Mã số sinh viên</label
                        ><input
                          class="form-control col-md-9"
                          id="studentId"
                          name="studentId"
                          type="text"
                          placeholder="{{item.studentId}}"
                        />
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="studentName"
                          >Họ Tên</label
                        ><input
                          class="form-control col-md-9"
                          id="studentName"
                          name="studentName"
                          type="text"
                          placeholder="{{item.studentName}}"
                        />
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="dob">Ngày sinh</label
                        ><input
                          class="form-control col-md-9"
                          id="dob"
                          name="dob"
                          type="text"
                          placeholder="{{item.dob}}"
                        />
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="gender"> Giới tính </label> 
                            ><input
                              class="form-control col-md-9"
                              id="gender"
                              type="text"
                              name="gender"
                              placeholder="{{item.gender}}"
                              
                            />
                        <div class="form-control-feedback"></div>
                      </div>
                           
                        
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="course">Khóa</label
                        ><input
                          class="form-control col-md-9"
                          id="course"
                          name="course"
                          type="text"
                          placeholder="{{item.course}}"
                    
                        />
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="department">Khoa</label
                        ><input
                          class="form-control col-md-9"
                          id="department"
                          name="department"
                          type="text"
                          placeholder="{{item.department}}"
                        
                        />
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="studentClass">Lớp</label
                        ><input
                          class="form-control col-md-9"
                          id="studentClass"
                          name="studentClass"
                          type="text"
                          placeholder="{{item.studentClass}}"
                        
                        />
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="email">Email</label
                        ><input
                          class="form-control col-md-9"
                          id="email"
                          name="email"
                          type="email"
                          placeholder="{{item.email}}"
                        
                        />
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="nationalId"
                          >CMND/CCCD</label
                        ><input
                          class="form-control col-md-9"
                          id="nationalId"
                          name="nationalId"
                          type="text"
                          placeholder="{{item.nationalId}}"
                        />
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="issuedDt"
                          >Ngày Cấp</label
                        ><input
                          class="form-control col-md-9"
                          id="issuedDt"
                          name="issuedDt"
                          type="text"
                          placeholder="{{item.issuedDt}}"
                        />
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="issuedPlace"
                          >Nơi Cấp</label
                        ><input
                          class="form-control col-md-9"
                          id="issuedPlace"
                          name="issuedPlace"
                          placeholder="{{item.issuedPlace}}"
                        />
                       
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="phone">Điện Thoại</label
                        ><input
                          class="form-control col-md-9"
                          id="phone"
                          name="phone"
                          type="tel"
                          placeholder="{{item.phone}}"
                        />
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="ethnic">Dân Tộc</label
                        ><input
                          class="form-control col-md-9"
                          id="ethnic"
                          name="ethnic"
                          placeholder="{{item.ethnic}}"
                        />
                       
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label" for="religion"
                          >Tôn Giáo</label
                        ><input
                          class="form-control col-md-9"
                          id="religion"
                          name="religion"
                          placeholder="{{item.religion}}"
                        />
                        
                        
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="control-label"  for="Address" >Địa Chỉ Thường Trú</label
                        ><textarea
                          class="form-control col-md-9"
                          id="street"
                          name="street"
                          rows="1"
                          placeholder="{{item.Address}}"
                        ></textarea>
                  
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                  </div>
    
                  <h4>Đăng ký Ký túc xá</h4>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label for="dormId">Ký túc xá</label
                        ><input
                          class="form-control col-md-9"
                          id="dormId"
                          name="dormId"
                          placeholder="{{item.dormId}}"
                        />
                        <div class="form-control-feedback"></div>
                      </div>
                    </div>
                  </div>
              </div>

      </main>
    </body>
</html>
{% endfor %}
{% endblock %}

website/templates/home.html
{% extends "sidenav.html" %}{% block title %}Home{% endblock %} {% block content%} 
<!DOCTYPE html>
<html>
  <title>W3.CSS</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="{{ url_for('static', filename='FileCss/style.css')}}" />

  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <body>


    <div class="containers">
    <div 
      id="carouselExampleControls"
      class="carousel slide"
      data-bs-ride="carousel"
    >
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="https://www.anphatpc.com.vn/media/news/0812_wp4676582-4k-pc-wallpapers.jpg" class="d-block w-100" alt="..." />
        </div>
        <div class="carousel-item">
          <img src="https://i.pinimg.com/originals/14/f1/55/14f15590d4723f4826076d0620979cfa.jpg" class="d-block w-100" alt="..." />
        </div>
        <div class="carousel-item">
          <img src="https://marmotamaps.com/de/fx/wallpaper/download/faszinationen/Marmotamaps_Wallpaper_Berchtesgaden_Desktop_1920x1080.jpg" class="d-block w-100" alt="..." />
        </div>
      </div>
      <button
        class="carousel-control-prev"
        type="button"
        data-bs-target="#carouselExampleControls"
        data-bs-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button
        class="carousel-control-next"
        type="button"
        data-bs-target="#carouselExampleControls"
        data-bs-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}

  {% for message in get_flashed_messages() %}
	
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  
    
  {% endfor %}

    <form method="POST">
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Nhập email"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Nhập password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
    {% endblock %}

website/templates/profile.html
{% extends 'base.html' %}

{% block content %}




	<h2>Profile</h2>
	<br/>

	<div class="card">
  <div class="card-header">
    {{ current_user.name }}
  </div>
  <div class="card-body">
   
    <p class="card-text">

<div class="container">
	<div class="row">
		<div class="col-8">

	<strong>User Id:</strong>
	{{ current_user.id }}<br/>

	<strong>Username:</strong>
	{{ current_user.first_name }}<br/>

	<strong>StudentId:</strong>
	{{ current_user.studentId }}<br/>

	<strong>Email:</strong>
	{{ current_user.email }}<br/>


{% endblock %}

website/templates/sidenav.html

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  
    <link rel="stylesheet" href="{{ url_for('static', filename='FileCss/style.css')}}" />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <style>
      .navbar-nav {
        margin: 0px;
        overflow: hidden;
        background-color: #111;
        position: fixed;
        top: 0px;
        right: 0px;
        width: 100%;
        z-index: 1030;
        
      }
      .navbar-nav a {
        margin: 10px;
        
      }
    </style>
  </head>
  <body>
    
    <div class="sidenav">
        <a href="/dknoitru">Đăng ký nội trú KTX</a>
        <a href="/thanhtoan">Thanh toán tiền phòng</a>
        <a href="/dondk">Đơn đăng ký </a>
        <a href="/profile" >Profile</a>
    </div>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
        </div>
      </div>
    </nav>

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>
    
   

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}

  {% for message in get_flashed_messages() %}
	
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  
    
  {% endfor %}


    <form method="POST">
      <h3 align="center">Sign Up</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Nhập email"
        />
      </div>
      <div class="form-group">
        <label for="firstName">First Name</label>
        <input
          type="text"
          class="form-control"
          id="firstName"
          name="firstName"
          placeholder="Nhập Tên"
        />
      </div>
      <div class="form-group">
        <label for="studentId">StudentId</label>
        <input
          type="text"
          class="form-control"
          id="studentId"
          name="studentId"
          placeholder="Nhập mã SV"
        />
      </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          placeholder="Nhập password"
        />
      </div>
      <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          placeholder="Xác thực password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endblock %}